name: Validate static

on:
  pull_request:
  push:
    branches: [master]

jobs:
  validate-static:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - run: sudo apt-get update
    - run: sudo apt-get -y install libxml2-utils yajl-tools
    - run: npm install

    - name: validate static
      run: ./validate_static
